### ISSUE TITLE
Running plinth fails with "ImportError: cannot import name 'LoginView'"

### ISSUE THREAD

**Issue by harry-7** [freedombox/Plinth#1057]
With the current master branch. I get this error when I do a `sudo ./run --debug`. 
```
[2017-10-10 07:41:16,746] plinth.__main__ DEBUG    Configured Django with applications - ['bootstrapform', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'stronghold', 'plinth', 'plinth.modules.avahi', 'plinth.modules.bind', 'plinth.modules.config', 'plinth.modules.datetime', 'plinth.modules.deluge', 'plinth.modules.diagnostics', 'plinth.modules.dynamicdns', 'plinth.modules.ejabberd', 'plinth.modules.firewall', 'plinth.modules.first_boot', 'plinth.modules.help', 'plinth.modules.ikiwiki', 'plinth.modules.infinoted', 'plinth.modules.jsxc', 'plinth.modules.letsencrypt', 'plinth.modules.minetest', 'plinth.modules.monkeysphere', 'plinth.modules.mumble', 'plinth.modules.names', 'plinth.modules.networks', 'plinth.modules.openvpn', 'plinth.modules.pagekite', 'plinth.modules.power', 'plinth.modules.privoxy', 'plinth.modules.quassel', 'plinth.modules.radicale', 'plinth.modules.repro', 'plinth.modules.roundcube', 'plinth.modules.security', 'plinth.modules.snapshot', 'plinth.modules.syncthing', 'plinth.modules.tor', 'plinth.modules.transmission', 'plinth.modules.ttrss', 'plinth.modules.upgrades', 'plinth.modules.users', 'plinth.modules.sso', 'plinth.modules.tahoe', 'plinth.modules.storage', 'plinth.modules.ssh', 'plinth.modules.matrixsynapse', 'plinth.modules.apache']
[2017-10-10 07:41:16,747] plinth.__main__ DEBUG    Creating or adding new tables to data file
Operations to perform:
  Apply all migrations: auth, contenttypes, plinth
Running migrations:
  No migrations to apply.
[2017-10-10 07:41:16,912] plinth.__main__ INFO     Configuration loaded from file - /etc/plinth/plinth.config
[2017-10-10 07:41:16,913] plinth.__main__ INFO     Script prefix - /plinth
[2017-10-10 07:41:17,564] plinth.module_loader DEBUG    No URLs for users
Traceback (most recent call last):
  File "./run", line 21, in <module>
    plinth.__main__.main()
  File "/vagrant/plinth/__main__.py", line 362, in main
    module_loader.include_urls()
  File "/vagrant/plinth/module_loader.py", line 44, in include_urls
    _include_module_urls(module_import_path, module_name)
  File "/vagrant/plinth/module_loader.py", line 121, in _include_module_urls
    r'', django.conf.urls.include((url_module, module_name)))]
  File "/usr/lib/python3/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/vagrant/plinth/modules/users/urls.py", line 27, in <module>
    from plinth.modules.sso.views import SSOLoginView, SSOLogoutView
  File "/vagrant/plinth/modules/sso/views.py", line 29, in <module>
    from django.contrib.auth.views import LoginView, LogoutView
ImportError: cannot import name 'LoginView'
```
After I did a bit of googling I found this [thread](https://stackoverflow.com/questions/38195526/cannot-import-loginview)
> There's no view called LoginView in django.contrib.auth.views I think you need.
from django.contrib.auth.views import login

I am testing freedombox on a vagrant box. Is this a problem with vagrant ?

**Comment by JosephKiranBabu** [comment]
@harry-7 You're probably on django-1.10. LoginView was introduced in 1.11
Just doing an `apt install plinth` should install the necessary dependencies on the box.

**Comment by harry-7** [comment]
@JosephKiranBabu  but why does this happen with a new box ? I did a `vagrant destroy` and then created a box.  Should we update the box?

**Comment by JosephKiranBabu** [comment]
The latest _dev_ box on vagrant cloud is still with Plinth 0.14. Hence, it still has dependencies corresponding to Plinth 0.14. If you just install Plinth 0.15.2, which is the latest, the necessary dependencies should automatically get installed on the box. 

We'll have to upload a new box to Vagrant Cloud.

**Comment by harry-7** [comment]
@JosephKiranBabu  Lets create a TODO or an issue to address this .. what say @jvalleroy

**Comment by JosephKiranBabu** [comment]
Yeah, we need a dev image for Vagrant Cloud and an update on the http://freedomboxfoundation.org/ page, since that's the first result that most people who just discovered FreedomBox usually find.

**Comment by harry-7** [comment]
@JosephKiranBabu  I updated the requirements of django to be >= 1.11 and created a PR. Please take a look at it.

**Comment by JosephKiranBabu** [comment]
Django version has been updated to 1.11 in the Debian package as well. Can this issue now be closed?

**Comment by harry-7** [comment]
What about the vagrant box? If the new one is available then i think we can close it

**Comment by JosephKiranBabu** [comment]
@harry-7 A new version of the Vagrant box was released 5 days ago.
https://app.vagrantup.com/freedombox/boxes/plinth-dev

**Comment by harry-7** [comment]
Okay closing this then

**Comment by JosephKiranBabu** [comment]
@jvalleroy When I try to download the new vagrant image, it's still picking up the 0.14.0 image. Maybe because it is still marked as "currently released version"?

![screenshot from 2017-10-19 12-45-40](https://user-images.githubusercontent.com/4830191/31758539-7ce26a2c-b4cb-11e7-933a-8d2cc302c377.png)

**Comment by jvalleroy** [comment]
@JosephKiranBabu I didn't upload 0.15.2, so it was unreleased. I think it will be better to upload 0.15.3 when it's available.

**Comment by jvalleroy** [comment]
I have updated the vagrant box to 0.15.3.

**Comment by harry-7** [comment]
Seems like everything is fixed. Closing this
