### ISSUE TITLE
Allow package install during first setup?

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1071]
When updating vagrant to the latest plinth master, I find that plinth gets stuck in startup loop:
```
[2017-10-17 10:52:41,449] plinth.setup   INFO     Will try again in 10 seconds
[2017-10-17 10:52:51,464] plinth.setup   INFO     Running first setup.
[2017-10-17 10:52:51,466] plinth.setup   INFO     Running setup for modules, essential - True, selected modules - None
[2017-10-17 10:52:51,488] plinth.setup   INFO     Running module setup - sso
[2017-10-17 10:52:51,723] plinth.setup   ERROR    Error running setup - libapache2-mod-auth-pubtkt
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 85, in run
    self.module.setup(self, old_version=current_version)
  File "/usr/local/lib/python3.6/dist-packages/plinth/modules/sso/__init__.py", line 37, in setup
    helper.install(managed_packages)
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 105, in install
    raise PackageNotInstalledError(package_name)
plinth.errors.PackageNotInstalledError: libapache2-mod-auth-pubtkt
[2017-10-17 10:52:51,724] plinth.setup   ERROR    Error running setup - libapache2-mod-auth-pubtkt
[2017-10-17 10:52:51,724] plinth.setup   WARNING  Unable to complete setup: libapache2-mod-auth-pubtkt
[2017-10-17 10:52:51,724] plinth.setup   INFO     Will try again in 10 seconds
```
Would it make sense to allow package installs here? It shouldn't affect normal systems, because the packages would already be installed as plinth dependencies. But it would be nice for vagrant development purpose.

**Comment by SunilMohanAdapa** [comment]
Not trying to package install during "first setup" addresses the following:
- On first boot of FreedomBox, we may not have network available. Trying to do `apt update` fails.  We do `apt update` before every install.
- Even when network is available, we may be contending with other processes trying to acquire dpkg lock. This is not a serious problem as we keep retrying.  However, we want to present the first run wizard to the user as soon as possible. This is not possible until we finish the first setup mechanism.

Also note that we are doing proper package installs when the setup process is not "first setup" mode. So, when upgrading a non-essential module with new dependency or when upgrading an essential package with an extra dependency proper package installation will happen. However, we will be in "first setup" mode when an extra essential module turns up.

Perhaps it would be okay to perform the following as part of vagrant provision (also telling users to do the same in README):
```
apt install `./run --list-dependencies`
```
