### ISSUE TITLE
Not able to access Plinth on localhost:4430/plinth

### ISSUE THREAD

**Issue by pranaygupta36** [freedombox/Plinth#1072]
I was trying to set up the development environment for Plinth using vagrant. After using vagrant up i am not able to access Plinth on https://localhost:4430/plinth/
and localhost:4430 showed this.
```
HTTP/1.1 400 Bad Request
Date: Tue, 17 Oct 2017 13:55:09 GMT
Server: Apache/2.4.25 (Debian)
Content-Length: 302
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at 127.0.1.1 Port 443</address>
</body></html>
```
Can someone please suggest me how to proceed.

**Comment by jvalleroy** [comment]
@pranaygupta36 I would suggest trying to start plinth directly in the vagrant box, and see what error it produces:
```
$ vagrant ssh
$ cd /vagrant/
$ sudo ./run
```

**Comment by pranaygupta36** [comment]
This is what I get when i do the above.
`[2017-10-17 16:10:15,836] plinth.__main__ INFO     Configuration loaded from file - /etc/plinth/plinth.config
[2017-10-17 16:10:15,837] plinth.__main__ INFO     Script prefix - /plinth
[2017-10-17 16:10:16,049] plinth.module_loader INFO     Module load order - ['security', 'names', 'pagekite', 'mumble', 'apache', 'sso', 'first_boot', 'matrixsynapse', 'jsxc', 'letsencrypt', 'monkeysphere', 'transmission', 'firewall', 'config', 'repro', 'shaarli', 'ssh', 'power', 'storage', 'restore', 'avahi', 'minetest', 'users', 'diagnostics', 'openvpn', 'ejabberd', 'ttrss', 'networks', 'privoxy', 'infinoted', 'tahoe', 'upgrades', 'snapshot', 'radicale', 'tor', 'deluge', 'datetime', 'help', 'bind', 'roundcube', 'syncthing', 'quassel', 'ikiwiki', 'dynamicdns']
[2017-10-17 16:10:16,060] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
Unit pagekite.service could not be found.
[2017-10-17 16:10:16,312] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
[2017-10-17 16:10:16,574] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/dynamicdns', 'status']
[2017-10-17 16:10:16,620] plinth.setup   INFO     Running first setup.
[2017-10-17 16:10:16,620] plinth.__main__ INFO     Setting up CherryPy server
[2017-10-17 16:10:16,621] plinth.setup   INFO     Running setup for modules, essential - True, selected modules - None
[2017-10-17 16:10:16,629] plinth.setup   INFO     Running module setup - security
[2017-10-17 16:10:16,832] plinth.setup   ERROR    Error running setup - fail2ban
Traceback (most recent call last):
  File "/vagrant/plinth/setup.py", line 85, in run
    self.module.setup(self, old_version=current_version)
  File "/vagrant/plinth/modules/security/__init__.py", line 50, in setup
    helper.install(managed_packages)
  File "/vagrant/plinth/setup.py", line 105, in install
    raise PackageNotInstalledError(package_name)
plinth.errors.PackageNotInstalledError: fail2ban
[2017-10-17 16:10:16,838] plinth.setup   ERROR    Error running setup - fail2ban
[2017-10-17 16:10:16,838] plinth.setup   WARNING  Unable to complete setup: fail2ban
[2017-10-17 16:10:16,839] plinth.setup   INFO     Will try again in 10 seconds
[17/Oct/2017:16:10:16] ENGINE Listening for SIGHUP.
[17/Oct/2017:16:10:16] ENGINE Listening for SIGTERM.
[17/Oct/2017:16:10:16] ENGINE Listening for SIGUSR1.
[17/Oct/2017:16:10:16] ENGINE Bus STARTING
[17/Oct/2017:16:10:16] ENGINE Started monitor thread '_TimeoutMonitor'.
[17/Oct/2017:16:10:22] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f146bf6ea58>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
OSError: Port 8000 not free on '127.0.0.1'

[17/Oct/2017:16:10:22] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("Port 8000 not free on '127.0.0.1'",)

[17/Oct/2017:16:10:22] ENGINE Bus STOPPING
[17/Oct/2017:16:10:22] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8000)) already shut down
[17/Oct/2017:16:10:22] ENGINE Stopped thread '_TimeoutMonitor'.
[17/Oct/2017:16:10:22] ENGINE Bus STOPPED
[17/Oct/2017:16:10:22] ENGINE Bus EXITING
[17/Oct/2017:16:10:22] ENGINE Bus EXITED
`

**Comment by JosephKiranBabu** [comment]
There's a temporary fix for this, though the permanent fix is to upload a new version of the vagrant box with Plinth 0.15.3
Login to your vagrant box and switch to root.
`$ vagrant ssh`

`$ sudo su - `

Install the latest plinth which also installs all of its dependencies.
```
# apt install plinth
# systemctl stop plinth
# cd /vagrant
# ./setup.py install
# ./run --debug
```

**Comment by SunilMohanAdapa** [comment]
Change in #1076 will ensure that `vagrant provision` will install new dependencies brought in by new packages.

@pranaygupta36 note that you will need to run `sudo systemctl stop plinth` before running `sudo ./run --debug` to avoid the system daemon which is already running from fighting with the one you are running on the command line for the same port.

**Comment by SunilMohanAdapa** [comment]
In addition to @JosephKiranBabu 's steps, you will need to run:

sudo apt install $(./run --list-dependencies)

**Comment by pranaygupta36** [comment]
@JosephKiranBabu  ./run --debug failed with an error. Cannot import LoginView.
`[2017-10-18 08:09:40,138] plinth.__main__ DEBUG    Configured Django with applications - ['bootstrapform', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'stronghold', 'plinth', 'plinth.modules.avahi', 'plinth.modules.ttrss', 'plinth.modules.users', 'plinth.modules.upgrades', 'plinth.modules.security', 'plinth.modules.sso', 'plinth.modules.snapshot', 'plinth.modules.shaarli', 'plinth.modules.names', 'plinth.modules.privoxy', 'plinth.modules.openvpn', 'plinth.modules.matrixsynapse', 'plinth.modules.quassel', 'plinth.modules.ejabberd', 'plinth.modules.syncthing', 'plinth.modules.transmission', 'plinth.modules.pagekite', 'plinth.modules.first_boot', 'plinth.modules.firewall', 'plinth.modules.ssh', 'plinth.modules.config', 'plinth.modules.tor', 'plinth.modules.roundcube', 'plinth.modules.minetest', 'plinth.modules.storage', 'plinth.modules.monkeysphere', 'plinth.modules.networks', 'plinth.modules.ikiwiki', 'plinth.modules.infinoted', 'plinth.modules.dynamicdns', 'plinth.modules.restore', 'plinth.modules.radicale', 'plinth.modules.datetime', 'plinth.modules.letsencrypt', 'plinth.modules.jsxc', 'plinth.modules.repro', 'plinth.modules.apache', 'plinth.modules.tahoe', 'plinth.modules.mumble', 'plinth.modules.diagnostics', 'plinth.modules.power', 'plinth.modules.deluge', 'plinth.modules.help', 'plinth.modules.bind']
[2017-10-18 08:09:40,139] plinth.__main__ DEBUG    Creating or adding new tables to data file
Operations to perform:
  Apply all migrations: auth, contenttypes, plinth
Running migrations:
  No migrations to apply.
[2017-10-18 08:09:40,253] plinth.__main__ INFO     Configuration loaded from file - /etc/plinth/plinth.config
[2017-10-18 08:09:40,254] plinth.__main__ INFO     Script prefix - /plinth
[2017-10-18 08:09:40,267] plinth.module_loader DEBUG    No URLs for users
Traceback (most recent call last):
  File "./run", line 21, in <module>
    plinth.__main__.main()
  File "/vagrant/plinth/__main__.py", line 361, in main
    module_loader.include_urls()
  File "/vagrant/plinth/module_loader.py", line 44, in include_urls
    _include_module_urls(module_import_path, module_name)
  File "/vagrant/plinth/module_loader.py", line 121, in _include_module_urls
    r'', django.conf.urls.include((url_module, module_name)))]
  File "/usr/lib/python3/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/vagrant/plinth/modules/users/urls.py", line 27, in <module>
    from plinth.modules.sso.views import SSOLoginView, SSOLogoutView
  File "/vagrant/plinth/modules/sso/views.py", line 29, in <module>
    from django.contrib.auth.views import LoginView, LogoutView
ImportError: cannot import name 'LoginView'`

@SunilMohanAdapa i was getting `Cannot initiate the connection to deb.debian.org:80 (2001:41c8:1000:21::21:4). - connect (101: Network is unreachable) [IP: 2001:41c8:1000:21::21:4 80]`

**Comment by pranaygupta36** [comment]
@JosephKiranBabu i was getting `ImportError: No module named 'axes'` on running` ./run --debug.`
i was getting the same error with on running  `sudo apt install $(./run --list-dependencies)`
`Traceback (most recent call last):
  File "./run", line 21, in <module>
    plinth.__main__.main()
  File "/vagrant/plinth/__main__.py", line 368, in main
    configure_django()
  File "/vagrant/plinth/__main__.py", line 289, in configure_django
    django.setup(set_prefix=True)
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python3/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'axes'`

**Comment by jvalleroy** [comment]
@pranaygupta36 You need the python3-django-axes package.

Also I have updated the vagrant box to 0.15.3.

**Comment by pranaygupta36** [comment]
thanks @jvalleroy  it is now working i properly.
