### ISSUE TITLE
users: ssh login test failures

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1083]
I get the following failures when running tests in vagrant:
```
======================================================================
FAIL: test_change_user_password (plinth.modules.users.tests.test_actions.TestActions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/plinth/modules/users/tests/test_actions.py", line 174, in test_change_user_password
    self.assertTrue(try_login_to_ssh(username, new_password))
AssertionError: False is not true

======================================================================
FAIL: test_create_user (plinth.modules.users.tests.test_actions.TestActions)
Test whether creating a new user works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/plinth/modules/users/tests/test_actions.py", line 157, in test_create_user
    self.assertTrue(try_login_to_ssh(username, password))
AssertionError: False is not true

======================================================================
FAIL: test_rename_user (plinth.modules.users.tests.test_actions.TestActions)
Test whether renaming a user works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/plinth/modules/users/tests/test_actions.py", line 191, in test_rename_user
    self.assertTrue(try_login_to_ssh(new_username, password))
AssertionError: False is not true
```

**Comment by jvalleroy** [comment]
Is there possibly an issue with setting users' password in LDAP?

When testing a new image build, I am not able to login through console or SSH with users added through plinth. I can only login after setting a password for fbx user.

**Comment by jvalleroy** [comment]
For the image I am testing, I found that slapd was not running. After starting it, I am able to login through SSH with a user created through plinth.

**Comment by jvalleroy** [comment]
It looks like both slapd and nslcd were disabled, so they did not start automatically.

**Comment by JosephKiranBabu** [comment]
@jvalleroy I think I saw this happen on my Vagrant box recently.

**Comment by jvalleroy** [comment]
@JosephKiranBabu Although I still don't understand the root cause, I have a patch to workaround the user login issue:
https://github.com/jvalleroy/plinth-debian/blob/master/debian/patches/0004-enable-login-services.patch
I built an image with this patch applied, and was able to login as expected.
