### ISSUE TITLE
letsencrypt: tests require sudo

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1084]
The letsencrypt tests require root privileges. They should be skipped unless running as root.

**Comment by jvalleroy** [comment]
To add more detail, I get this error when building plinth 0.15.3 package:
```
ERROR: test_add_valid_domain (plinth.modules.letsencrypt.tests.test_domain_name_changes.TestDomainNameChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/plinth-0.15.3+ds/plinth/modules/letsencrypt/tests/test_domain_name_changes.py", line 35, in test_add_valid_domain
    on_domain_added('test', 'domainname', 'subdomain.domain.tld'))
  File "/build/plinth-0.15.3+ds/plinth/modules/letsencrypt/__init__.py", line 160, in on_domain_added
    for domain_name, domain_status in get_status()['domains'].items():
  File "/build/plinth-0.15.3+ds/plinth/modules/letsencrypt/__init__.py", line 193, in get_status
    status = actions.superuser_run('letsencrypt', ['get-status'])
  File "/build/plinth-0.15.3+ds/plinth/actions.py", line 117, in superuser_run
    return _run(action, options, input, async, True)
  File "/build/plinth-0.15.3+ds/plinth/actions.py", line 183, in _run
    shell=False)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
```
