### ISSUE TITLE
letsencrypt: internal server error when obtaining certificate

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#1103]
Testing with plinth 0.15.3, I ran into the following error when obtaining a new LE certificate:

```
[2017-10-28 12:58:34,864] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'obtain', '--domain', 'test2.makelist.de']
Internal Server Error: /plinth/sys/letsencrypt/obtain/test2.makelist.de/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/vagrant/plinth/modules/letsencrypt/views.py", line 77, in obtain
    enable_renewal_management(request, domain)
  File "/vagrant/plinth/modules/letsencrypt/views.py", line 87, in enable_renewal_management
    if domain == config.get_domainname():
AttributeError: module 'plinth.modules.config' has no attribute 'get_domainname'
```

The fix is one-line change, and I'll upload the fix shortly. This is just to document the issue, in case other people run into this bug.

**Comment by jvalleroy** [comment]
I opened #1105 for refactoring the config module.
