### ISSUE TITLE
0.15.3 testing update/upgrade broken.

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#1200]
I'm running `Debian GNU/Linux buster/sid and Plinth version 0.15.3. Plinth is up to date. ` – at least that is what the /about tells me.

Tryng to trigger an update via plinth gives me this result:

```
2018-01-13 17:04:05,859 INFO Initial whitelisted packages: 
2018-01-13 17:04:05,861 INFO Starting unattended upgrades script
2018-01-13 17:04:05,862 INFO Allowed origins are: ['origin=Debian', 'origin=Debian,codename=sid,label=Debian-Security']
2018-01-13 17:04:50,030 INFO No packages found that can be upgraded unattended and no pending auto-removals
```

ssh'ing into my FreedomBox and trying to trigger an update says:

```
~$ sudo apt update
0% [Working]E: could not load seccomp policy: Invalid argument - HttpMethod::Configuration (22: Invalid argument)
Reading package lists... Done
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (100)
```

Shouldn't plinth be udpated? Seems like something is awfully wrong to me.

**Comment by mray** [comment]
My FreedomBox stopped running eventually and after a reboot the Matrix servers stopped running, asking for a click on an update-button. After clicking this is what I get:
![image](https://user-images.githubusercontent.com/164785/34960044-800af5da-fa39-11e7-95d6-7aea2c75110b.png)

What can I do?!? I tried apt with `clean`, `dist-upgrade` and `install -f` and  `dpkg --configure -a` without any success.

I miss my matrix server :'(

**Comment by mray** [comment]
I noticed plinth shows for a **sort time**:

![image](https://user-images.githubusercontent.com/164785/34960662-0b954b9e-fa3c-11e7-87cc-5b16f5a4b778.png)

so I tried to install those packages myself. "matrix-synapse" was already the latest version but the other triggerd a problem:

```
~$ sudo apt install matrix-synapse-ldap3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-ldap3
The following NEW packages will be installed:
  matrix-synapse-ldap3 python-ldap3
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 220 kB of archives.
After this operation, 2.040 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
0% [Working]E: could not load seccomp policy: Invalid argument - HttpMethod::Configuration (22: Invalid argument)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (100)

```

**Comment by jvalleroy** [comment]
@mray Could you please run ```uname -a``` and share the result?

**Comment by mray** [comment]
```
~$ uname -a  
Linux freedombox 4.4.45-v7+ #954 SMP Fri Jan 27 19:06:40 GMT 2017 armv7l GNU/Linux
```

**Comment by jvalleroy** [comment]
It looks like you are using the "old" raspberry2 image. This image was built before we could use a Debian-packaged kernel, so the kernel provided by the RPi Foundation was installed using rpi-update. The new "stable" image uses the kernel from Debian instead. If possible to switch to the new image, I would recommend that.

One disadvantage of the old image is that, since the kernel is not from the Debian repository, it doesn't get upgraded by apt. It looks like the kernel you are running is quite old (compare to 4.9 which is in stable now). You could try to upgrade to the latest kernel from RPi Foundation, by running ```sudo rpi-update```. (I don't know if this will fix the apt issue though.)

If you continue with this image, I'd suggest running ```sudo rpi-update``` occasionally to ensure the kernel is up to date.

**Comment by mray** [comment]
I'd **love** to switch to a new image - since I can have snapshots and btrfs support – but what about all my user data? I have no clue how to successfully and reliably move radicale and ejabberd over. I also use DynDNS, Matrix and Minetest.

I'm aware that moving apps / changin harware is an issue. So I guess this is a bad day for me. 

So are we going to treat this as a WONTFIX and just move on as if nothing happens? (in order to close this issue)

**Comment by SunilMohanAdapa** [comment]
On Tuesday 16 January 2018 06:15 AM, mray wrote:
> I'd *love* to switch to a new image - since I can have snapshots and
> btrfs support – but what about all my user data? I have no clue how to
> successfully and reliably move radicale and ejabberd over. I also use
> DynDNS, Matrix and Minetest.
> 
> I'm aware that moving apps / changin harware is an issue. So I guess
> this is a bad day for me.
> 
> So are we going to treat this as a WONTFIX and just move on as if
> nothing happens? (in order to close this issue)

We can help you transfer data from the above services to a new image. It
won't be straight forward but while we are at it we can document the
process so that it is useful for us later.

-- 
Sunil

**Comment by mray** [comment]
@jvalleroy `sudo rpi-update` did update the kernel, thanks. Still having issues to update and get Snypse running properly. Will have to investigate more.

@SunilMohanAdapa thanks for the offer. What would be sensible steps to start this undertaking? My main focus is to have a short radicale downtime.

**Comment by SunilMohanAdapa** [comment]
On Wednesday 17 January 2018 03:52 PM, mray wrote:
> @SunilMohanAdapa <https://github.com/sunilmohanadapa> thanks for the
> offer. What would be sensible steps to start this undertaking? My main
> focus is to have a short radicale downtime.

Perhaps we can focus on radicale first and get that available on new
system available first followed by other services. I am thinking this:

- Stop all services.
- Login via SSH and create tar of the data and copy it.
- Bring up new machine fresh, install the services.
- Login via SSH, copy data.
- Start restoring services one by one.

We can work on details of the setups for each service.

-- 
Sunil

**Comment by mray** [comment]
@SunilMohanAdapa 

>- Login via SSH and create tar of the data and copy it.

What exactly is the data I need to tar? (help on terminal commands would be welcome)

**Comment by SunilMohanAdapa** [comment]
On Wednesday 17 January 2018 09:04 PM, mray wrote:
> @SunilMohanAdapa <https://github.com/sunilmohanadapa>
> 
>       * Login via SSH and create tar of the data and copy it.
> 
> What exactly is the data I need to tar? (help on terminal commands would
> be welcome)

I have update the full information required for manual backup and
restore into the wiki page: https://wiki.debian.org/FreedomBox/Backups .
Please let me know if you need further details with any of the steps.

Perhaps do a trial with these steps.

-- 
Sunil

**Comment by mray** [comment]
Wow thanks a lot for whipping up all the documentation!

I'm still confused about how to get latest testing running on my Raspi2:

* As of @jvalleroy s note above I chose the stable version `freedombox-stable-nonfree_2017-07-17_raspberry2-armhf.img.xz` running Plinth 0.13.1. Other Images seemed to be older despite being testing, but this one seems to have the right kernel at least. I'm confused.
* I was running testing on 0.15.3 and recently noticed there is a 0.21.0 release – I'm confused on how to end up at the correct version/repo from 0.13 now.
* *(conflicting timestamps on the FTP server are confusing, too btw: https://ftp.freedombox.org/pub/freedombox/stable-2017.06/)*

I now run the said stable image with 0.13 but a `sudo apt dist-upgrade` does not seem to trigger an update:

```
~$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by jvalleroy** [comment]
@mray To move from stable to testing, you will need to edit /etc/sources/apt.list, and replace each instance of "stable" (or "stretch") with "testing". Then run "sudo apt dist-upgrade".

But I think you will run into a few issues with this approach. (These actually are bugs that need to be fixed.)
- If you get prompts about modified conffiles, choose "n" to keep the modifications.
- fail2ban has a conflict with firewalld. You may need to run "sudo systemctl stop fail2ban" and then retry the dist-upgrade.

Otherwise, I think @JosephKiranBabu is working on automatic weekly builds of testing images.

**Comment by mray** [comment]
@jvalleroy thanks! Your tips helped me to master the issues that popped up as you predicted. But, there is always this but:

* Radiacale refuses to install for a simple reason: `E: Unable to locate package radicale` - Is it still packaged in debain or what?!!?
* Synapse crashes plinth after I committed the cardinal sin of installing it without a proper domain name! Every time I visit the broken Snyapse app-page in plinth I have to reboot. Should I purge some packages and re-install now?

**Comment by jvalleroy** [comment]
According to https://tracker.debian.org/pkg/radicale, the package is missing from testing. That's due to the 2 open RC bugs. The package is still in unstable though.

If you want to install the package from unstable, you can add another line to your /etc/apt/sources.list - copy the line for testing, and replace "testing" with "unstable". (I think this package should be ok to use, despite the RC bugs.)

Regarding Synapse, could you explain how the page is broken? What is different before and after the reboot?

**Comment by mray** [comment]
Should I remove that line afterwards to avoid having my entire system in unstable?

@ Synapse page, this is what plinth gives me now:
![image](https://user-images.githubusercontent.com/164785/35167953-8f6d5e7a-fd57-11e7-8e97-6ee1c7c2d164.png)

The link to the log  shows this:

```
[2018-01-19 19:28:29,496] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/firewall', 'get-enabled-services', '--zone', 'internal']
[2018-01-19 19:28:34,120] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']
[2018-01-19 19:28:35,975] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy'], , 
[2018-01-19 19:28:36,110] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/firewall', 'get-enabled-services', '--zone', 'external']
[2018-01-19 19:28:40,495] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']
[2018-01-19 19:28:42,198] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy'], , 
[2018-01-19 19:28:42,987] plinth.modules.firewall INFO     Service enabled - radicale, True
[2018-01-19 19:28:42,989] plinth.setup   INFO     Running step for module - radicale, step - post
[2018-01-19 19:28:55,311] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/matrixsynapse', 'public_registration', 'status']
[2018-01-19 19:29:00,358] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/matrixsynapse', 'public_registration', 'status'], , Traceback (most recent call last):
  File "/usr/share/plinth/actions/matrixsynapse", line 139, in <module>
    main()
  File "/usr/share/plinth/actions/matrixsynapse", line 135, in main
    sub_command_method(arguments)
  File "/usr/share/plinth/actions/matrixsynapse", line 110, in subcommand_public_registration
    config = round_trip_load(config_file)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/main.py", line 685, in round_trip_load
    return load(stream, RoundTripLoader, version, preserve_quotes=preserve_quotes)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/main.py", line 636, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/usr/lib/python3/dist-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 106, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/usr/lib/python3/dist-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/parser.py", line 572, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 1620, in check_token
    self._gather_comments()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 1662, in _gather_comments
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 265, in fetch_more_tokens
    return self.fetch_block_entry()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 544, in fetch_block_entry
    self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: sequence entries are not allowed here
  in "/etc/matrix-synapse/homeserver.yaml", line 71, column 12

[2018-01-19 19:29:00,362] django.request ERROR    Internal Server Error: /plinth/apps/matrixsynapse/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/plinth/modules/matrixsynapse/views.py", line 75, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/lib/python3/dist-packages/plinth/modules/matrixsynapse/views.py", line 79, in get_context_data
    context = super().get_context_data(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/plinth/views.py", line 128, in get_context_data
    context = super().get_context_data(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/edit.py", line 93, in get_context_data
    kwargs['form'] = self.get_form()
  File "/usr/lib/python3/dist-packages/django/views/generic/edit.py", line 45, in get_form
    return form_class(**self.get_form_kwargs())
  File "/usr/lib/python3/dist-packages/django/views/generic/edit.py", line 52, in get_form_kwargs
    'initial': self.get_initial(),
  File "/usr/lib/python3/dist-packages/plinth/modules/matrixsynapse/views.py", line 88, in get_initial
    'enable_public_registration': get_public_registration_status()
  File "/usr/lib/python3/dist-packages/plinth/modules/matrixsynapse/__init__.py", line 162, in get_public_registration_status
    'status'])
  File "/usr/lib/python3/dist-packages/plinth/actions.py", line 117, in superuser_run
    return _run(action, options, input, async, True)
  File "/usr/lib/python3/dist-packages/plinth/actions.py", line 191, in _run
    raise ActionError(action, output, error)
plinth.errors.ActionError: ('matrixsynapse', '', 'Traceback (most recent call last):\n  File "/usr/share/plinth/actions/matrixsynapse", line 139, in <module>\n    main()\n  File "/usr/share/plinth/actions/matrixsynapse", line 135, in main\n    sub_command_method(arguments)\n  File "/usr/share/plinth/actions/matrixsynapse", line 110, in subcommand_public_registration\n    config = round_trip_load(config_file)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/main.py", line 685, in round_trip_load\n    return load(stream, RoundTripLoader, version, preserve_quotes=preserve_quotes)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/main.py", line 636, in load\n    return loader._constructor.get_single_data()  # type: ignore\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/constructor.py", line 102, in get_single_data\n    node = self.composer.get_single_node()\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 75, in get_single_node\n    document = self.compose_document()\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 96, in compose_document\n    node = self.compose_node(None, None)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node\n    node = self.compose_mapping_node(anchor)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 130, in compose_node\n    node = self.compose_sequence_node(anchor)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node\n    node.value.append(self.compose_node(node, index))\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node\n    node = self.compose_mapping_node(anchor)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 130, in compose_node\n    node = self.compose_sequence_node(anchor)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node\n    node.value.append(self.compose_node(node, index))\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node\n    node = self.compose_mapping_node(anchor)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 106, in compose_node\n    if self.parser.check_event(AliasEvent):\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/parser.py", line 144, in check_event\n    self.current_event = self.state()\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/parser.py", line 572, in parse_block_mapping_value\n    if self.scanner.check_token(ValueToken):\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 1620, in check_token\n    self._gather_comments()\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 1662, in _gather_comments\n    self.fetch_more_tokens()\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 265, in fetch_more_tokens\n    return self.fetch_block_entry()\n  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 544, in fetch_block_entry\n    self.reader.get_mark())\nruamel.yaml.scanner.ScannerError: sequence entries are not allowed here\n  in "/etc/matrix-synapse/homeserver.yaml", line 71, column 12\n')


```

**Comment by jvalleroy** [comment]
@mray Yes, best to comment out the "unstable" line with ```#```.

**Comment by mray** [comment]
Ok after quite some amount moving data around and creating new users and stopping and starting services, this is where I am:

* DynDNS works fine again (Let's encrypt works fine, too)
* Minetest Server is back up again and running fine
* Radicale correctly serves addresses and calendards to multiple devices 
* eJabberd also is *enabled* but **does not start**
* Synapse no longer triggers a broken plinth, and is *enabled* but **does not start**

This is what I tried  so far:

#### ejabberd
`sudo dpkg-reconfigure` and 

```
~$ sudo ejabberdctl start
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
su: Permission denied
(Ignored)
```
#### synapse

```
~$ sudo systemctl enable matrix-synapse
Synchronizing state of matrix-synapse.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable matrix-synapse
```

and then 

```
~$ sudo systemctl start matrix-synapse
```

nothing helps. Ejabberd and Synapse are dead despite my desperate attempts to revive them.

What else can I try?
