### ISSUE TITLE
Error 500 when trying to change something via plinth, extension of #1194

### ISSUE THREAD

**Issue by skai2701** [freedombox/Plinth#1210]
hello everybody, 
last time (#1194) the error 500 occurred when I wanted to configure  pagekite, but now the error occurs everywhere I want do configure something, the error message occurs always. I am still logged in, I can login via ssh - shell, but no configuration is possible. 
Besides, I cannot attach a file, here in github, error message: Something went really wrong, and we can't process that file.
so here the first file with pagekite, after that the next occurrence
#################################################
  ile "/usr/share/plinth/actions/cockpit", line 139, in <module>
    main()
  File "/usr/share/plinth/actions/cockpit", line 135, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/cockpit", line 104, in subcommand_add_domain
    origins = _get_origin_domains(aug)
  File "/usr/share/plinth/actions/cockpit", line 88, in _get_origin_domains
    return set(origins.split())
AttributeError: 'NoneType' object has no attribute 'split'

[2018-01-11 10:21:00,324] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/openvpn', 'is-setup']
[2018-01-11 10:21:04,971] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/dynamicdns', 'status']
[2018-01-11 10:21:06,089] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
[2018-01-11 10:21:19,809] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
[2018-01-11 10:21:33,661] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-frontend']
[2018-01-11 10:21:46,972] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/cockpit', 'add-domain', None]
[2018-01-11 10:21:46,993] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'get-status']
[2018-01-11 10:22:00,566] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'manage_hooks', 'status']
[2018-01-11 10:22:17,616] plinth.setup   INFO     Running regular setup.
[2018-01-11 10:22:17,619] plinth.__main__ INFO     Setting up CherryPy server
[2018-01-11 10:22:17,646] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']
[11/Jan/2018:10:22:18] ENGINE Listening for SIGTERM.
[11/Jan/2018:10:22:18] ENGINE Listening for SIGHUP.
[11/Jan/2018:10:22:18] ENGINE Listening for SIGUSR1.
[11/Jan/2018:10:22:18] ENGINE Bus STARTING
[11/Jan/2018:10:22:18] ENGINE Started monitor thread '_TimeoutMonitor'.
[11/Jan/2018:10:22:19] ENGINE Serving on http://127.0.0.1:8000
[11/Jan/2018:10:22:19] ENGINE Bus STARTED
[2018-01-11 10:22:21,944] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy'], , 
[2018-01-11 10:22:23,099] plinth.setup   INFO     Running setup for modules, essential - True, selected modules - None
[2018-01-11 10:22:23,422] plinth.setup   INFO     Setup thread finished.
[2018-01-11 10:27:36,036] axes.watch_login INFO     AXES: Calling decorated function: SSOLoginView
[2018-01-11 10:27:36,200] axes.watch_login INFO     AXES: Calling decorated function: bound_func
[2018-01-11 10:27:46,645] axes.watch_login INFO     AXES: Calling decorated function: SSOLoginView
[2018-01-11 10:27:46,756] axes.watch_login INFO     AXES: Calling decorated function: bound_func
[2018-01-11 10:27:48,104] axes.watch_login INFO     AXES: Successful login by {user: 'user', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2018-01-11 10:27:48,296] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/auth-pubtkt', 'generate-ticket', '--uid', 'user', '--private-key-file', '/etc/apache2/auth-pubtkt-keys/privkey.pem', '--tokens', 'admin']
[2018-01-11 10:27:54,092] axes.watch_login INFO     AXES: Successful login by {user: 'user', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2018-01-11 10:32:38,376] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']
[2018-01-11 10:32:41,766] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy'], , 
[2018-01-11 10:37:49,323] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
[2018-01-11 10:38:02,642] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
[2018-01-11 10:38:16,740] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-frontend']
[2018-01-11 10:38:30,899] django.request ERROR    Internal Server Error: /plinth/sys/pagekite/configure/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py", line 46, in bootstrap_horizontal
    return render(element, markup_classes)
  File "/usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py", line 83, in render
    return template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/lib/python3/dist-packages/django/template/context.py", line 287, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than Context.

##########################################################################
the next file begins here :

##########################################################################
[2017-12-08 20:30:54,366] axes.watch_login INFO     AXES: Repeated login failure by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Updating access record. Count = 1 of 3
[2017-12-08 20:30:54,616] axes.watch_login INFO     AXES: Repeated login failure by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Updating access record. Count = 2 of 3
[2017-12-08 20:31:08,265] axes.watch_login INFO     AXES: Calling decorated function: SSOLoginView
[2017-12-08 20:31:08,364] axes.watch_login INFO     AXES: Calling decorated function: bound_func
[2017-12-08 20:31:09,849] axes.watch_login INFO     AXES: Successful login by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2017-12-08 20:31:10,056] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/auth-pubtkt', 'generate-ticket', '--uid', 'sk', '--private-key-file', '/etc/apache2/auth-pubtkt-keys/privkey.pem', '--tokens', 'admin']
[2017-12-08 20:31:15,947] axes.watch_login INFO     AXES: Successful login by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2017-12-08 22:17:55,968] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/openvpn', 'is-setup']
[2017-12-08 22:18:13,510] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/openvpn', 'get-profile', 'sk', 'freedombox']
[2017-12-08 22:18:44,385] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'get-status']
[2017-12-08 22:18:58,448] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'manage_hooks', 'status']
[2017-12-31 10:57:40,709] axes.watch_login INFO     AXES: Calling decorated function: SSOLoginView
[2017-12-31 10:57:40,878] axes.watch_login INFO     AXES: Calling decorated function: bound_func
[2017-12-31 10:57:51,798] axes.watch_login INFO     AXES: Calling decorated function: SSOLoginView
[2017-12-31 10:57:51,899] axes.watch_login INFO     AXES: Calling decorated function: bound_func
[2017-12-31 10:57:53,357] axes.watch_login INFO     AXES: Successful login by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2017-12-31 10:57:53,574] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/auth-pubtkt', 'generate-ticket', '--uid', 'sk', '--private-key-file', '/etc/apache2/auth-pubtkt-keys/privkey.pem', '--tokens', 'admin']
[2017-12-31 10:57:59,781] axes.watch_login INFO     AXES: Successful login by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2017-12-31 10:59:46,839] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'create-user', 'skwiki']
[2017-12-31 10:59:53,598] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'create-user', 'skwiki'], , Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 371, in <module>
    main()
  File "/usr/share/plinth/actions/users", line 367, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/users", line 225, in subcommand_create_user
    _run(['ldapadduser', arguments.username, 'users'])
  File "/usr/share/plinth/actions/users", line 357, in _run
    return subprocess.run(arguments, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapadduser', 'skwiki', 'users']' returned non-zero exit status 1.

[2017-12-31 10:59:53,621] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'add-user-to-group', 'skwiki', 'wiki']
[2017-12-31 11:00:00,506] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'add-user-to-group', 'skwiki', 'wiki'], , Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 371, in <module>
    main()
  File "/usr/share/plinth/actions/users", line 367, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/users", line 331, in subcommand_add_user_to_group
    add_user_to_group(arguments.username, arguments.groupname)
  File "/usr/share/plinth/actions/users", line 326, in add_user_to_group
    _run(['ldapaddusertogroup', username, groupname])
  File "/usr/share/plinth/actions/users", line 357, in _run
    return subprocess.run(arguments, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapaddusertogroup', 'skwiki', 'wiki']' returned non-zero exit status 1.

[2017-12-31 11:59:28,049] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'get-status']
[2017-12-31 11:59:38,799] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'get-status']
[2017-12-31 11:59:46,411] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'manage_hooks', 'status']
[2017-12-31 12:00:06,332] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'manage_hooks', 'status']
[2018-01-17 10:26:19,183] axes.watch_login INFO     AXES: BEGIN LOG
[2018-01-17 10:26:19,207] axes.watch_login INFO     AXES: Using django-axes 2.3.3
[2018-01-17 10:26:19,214] axes.watch_login INFO     AXES: blocking by IP only.
[2018-01-17 10:26:23,297] plinth.__main__ INFO     Configuration loaded from file - /etc/plinth/plinth.config
[2018-01-17 10:26:23,317] plinth.__main__ INFO     Script prefix - /plinth
[2018-01-17 10:26:34,583] plinth.module_loader INFO     Module load order - ['cockpit', 'ikiwiki', 'networks', 'jsxc', 'diagnostics', 'privoxy', 'transmission', 'names', 'help', 'deluge', 'storage', 'minetest', 'ttrss', 'apache', 'power', 'ssh', 'snapshot', 'ejabberd', 'first_boot', 'radicale', 'repro', 'quassel', 'bind', 'syncthing', 'tahoe', 'security', 'firewall', 'config', 'tor', 'openvpn', 'upgrades', 'avahi', 'infinoted', 'monkeysphere', 'dynamicdns', 'letsencrypt', 'mumble', 'matrixsynapse', 'pagekite', 'users', 'roundcube', 'sso', 'datetime']
[2018-01-17 10:26:37,146] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/cockpit', 'add-domain', '']
[2018-01-17 10:26:42,015] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/cockpit', 'add-domain', ''], , Traceback (most recent call last):
  File "/usr/share/plinth/actions/cockpit", line 139, in <module>
    main()
  File "/usr/share/plinth/actions/cockpit", line 135, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/cockpit", line 104, in subcommand_add_domain
    origins = _get_origin_domains(aug)
  File "/usr/share/plinth/actions/cockpit", line 88, in _get_origin_domains
    return set(origins.split())
AttributeError: 'NoneType' object has no attribute 'split'

[2018-01-17 10:26:42,202] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/openvpn', 'is-setup']
[2018-01-17 10:26:46,983] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/dynamicdns', 'status']
[2018-01-17 10:26:48,091] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
[2018-01-17 10:27:01,283] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
[2018-01-17 10:27:14,072] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-frontend']
[2018-01-17 10:27:27,277] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/cockpit', 'add-domain', None]
[2018-01-17 10:27:27,329] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'get-status']
[2018-01-17 10:27:41,045] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'manage_hooks', 'status']
[2018-01-17 10:27:56,566] plinth.setup   INFO     Running regular setup.
[2018-01-17 10:27:56,570] plinth.__main__ INFO     Setting up CherryPy server
[2018-01-17 10:27:56,597] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']
[17/Jan/2018:10:27:57] ENGINE Listening for SIGTERM.
[17/Jan/2018:10:27:57] ENGINE Listening for SIGHUP.
[17/Jan/2018:10:27:57] ENGINE Listening for SIGUSR1.
[17/Jan/2018:10:27:57] ENGINE Bus STARTING
[17/Jan/2018:10:27:57] ENGINE Started monitor thread '_TimeoutMonitor'.
[17/Jan/2018:10:27:58] ENGINE Serving on http://127.0.0.1:8000
[17/Jan/2018:10:27:58] ENGINE Bus STARTED
[2018-01-17 10:28:00,831] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy'], , 
[2018-01-17 10:28:01,983] plinth.setup   INFO     Running setup for modules, essential - True, selected modules - None
[2018-01-17 10:28:02,310] plinth.setup   INFO     Setup thread finished.
[2018-01-17 10:32:47,634] axes.watch_login INFO     AXES: Calling decorated function: SSOLoginView
[2018-01-17 10:32:47,770] axes.watch_login INFO     AXES: Calling decorated function: bound_func
[2018-01-17 10:33:01,043] axes.watch_login INFO     AXES: Calling decorated function: SSOLoginView
[2018-01-17 10:33:01,166] axes.watch_login INFO     AXES: Calling decorated function: bound_func
[2018-01-17 10:33:02,617] axes.watch_login INFO     AXES: Successful login by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2018-01-17 10:33:02,801] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/auth-pubtkt', 'generate-ticket', '--uid', 'sk', '--private-key-file', '/etc/apache2/auth-pubtkt-keys/privkey.pem', '--tokens', 'admin']
[2018-01-17 10:33:08,547] axes.watch_login INFO     AXES: Successful login by {user: 'sk', ip: '192.168.0.3', user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', path: '/accounts/login/'}. Creating access record.
[2018-01-17 10:33:28,568] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/storage', 'is-partition-expandable', '/dev/mmcblk0p2']
[2018-01-17 10:33:31,430] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/storage', 'is-partition-expandable', '/dev/mmcblk0p2'], , 

:w

**Comment by SunilMohanAdapa** [comment]
On Wednesday 17 January 2018 04:18 PM, skai2701 wrote:
> Traceback (most recent call last):
> File "/usr/share/plinth/actions/cockpit", line 139, in
> main()
> File "/usr/share/plinth/actions/cockpit", line 135, in main
> subcommand_method(arguments)
> File "/usr/share/plinth/actions/cockpit", line 104, in subcommand_add_domain
> origins = _get_origin_domains(aug)
> File "/usr/share/plinth/actions/cockpit", line 88, in _get_origin_domains
> return set(origins.split())
> AttributeError: 'NoneType' object has no attribute 'split'

This one happens when there are no domains configured on the System ->
Configure page. Configuring one is a work around.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
On Wednesday 17 January 2018 04:18 PM, skai2701 wrote:
[...]
> subprocess.CalledProcessError: Command '['ldapadduser', 'skwiki',
> 'users']' returned non-zero exit status 1.
[...]
> subprocess.CalledProcessError: Command '['ldapaddusertogroup', 'skwiki',
> 'wiki']' returned non-zero exit status 1.
> 

Looks like the users module is having some trouble. Could you please
post the following additional information:

- Version of Plinth
- Results of running diagnostics on users module.
- Does the file /etc/ldapscripts/freedombox-ldapscripts.conf exist?

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
On Thursday 18 January 2018 05:49 PM, skai2701 wrote:
[...]
>> - Version of Plinth --A----:there is no plinth -V, the date is Nov 7

Another way to check plinth version is `dpkg -l plinth`.

>> - Results of running diagnostics on users module. --A---: sorry, I
>> cannot start anything on plinth, always error  500
>> - Does the file /etc/ldapscripts/freedombox-ldapscripts.conf exist?
>> ---A---: NO

If Plinth or the rest of the system it outdated, could you please
upgrade to the latest version 0.20.0? The users' setup that is required
is also performed again and may fix the current problem you have.

-- 
Sunil
