### ISSUE TITLE
[765916] plinth: fails to start

### ISSUE THREAD

**Issue by FedericoCeratto** [freedombox/Plinth#132]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20141019083308.12018.82183.reportbug@test>
BTS author: broken <broken@yandex.com>

Package: plinth
Version: 0.3.2.0.git.20140829-1
Severity: important

Dear Maintainer,
*** Please consider answering these questions, where appropriate ***
Setting up plinth (0.3.2.0.git.20140829-1) ...
[....] Starting embedded web frontend: plinthTraceback (most recent call last):
  File "/usr/share/plinth/python/plinth/plinth.py", line 239, in <module>
    main()
  File "/usr/share/plinth/python/plinth/plinth.py", line 229, in main
    configure_django()
  File "/usr/share/plinth/python/plinth/plinth.py", line 213, in configure_django
    django.core.management.call_command('syncdb', interactive=False)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 93, in call_command
    app_name = get_commands()[name]
  File "/usr/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 73, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
 failed!
invoke-rc.d: initscript plinth, action "start" failed.
dpkg: error processing package plinth (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of freedombox-setup:
 freedombox-setup depends on plinth (>= 0.3.2.0.git.20140504-1); however:
  Package plinth is not configured yet.



*** End of the template - remove these lines ***


-- System Information:
Debian Release: jessie/sid
  APT prefers stable-updates
  APT policy: (500, 'stable-updates'), (500, 'testing'), (500, 'stable')
Architecture: amd64 (x86_64)

Kernel: Linux 3.2.0-4-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

Versions of packages plinth depends on:
ii  adduser                  3.113+nmu3
ii  libjs-jquery             1.7.2+dfsg-3.2
ii  libjs-modernizr          2.6.2+ds1-1
ii  libjs-twitter-bootstrap  2.0.2+dfsg-5
ii  python                   2.7.8-1
ii  python-bcrypt            0.4-2+b1
ii  python-bootstrapform     3.1.0-5
ii  python-cherrypy3         3.5.0-1
ii  python-django            1.7-3
ii  python-passlib           1.6.1-1
ii  python-withsqlite        0.0.0~git.20130929-1
ii  sudo                     1.8.10p3-1

plinth recommends no packages.

plinth suggests no packages.

-- Configuration Files:
/etc/sudoers.d/plinth [Errno 13] Permission denied: u'/etc/sudoers.d/plinth'

-- no debconf information

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <54578BAD.2010209@medhas.org>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

I believe, this bug is due to incompatibility with Django 1.7.  When
Django 1.7 got uploaded to unstable Plinth broke.  This has been fixed
upstream in release 0.4.1 of Plinth which requires and works with Django
1.7.  The newly uploaded Plinth package version 0.4.1-1 in unstable, I
believe, fixes this issue.

This bug report should be closed and reopened if the problem persists.

Thank you for reporting the issue.

-- 
Sunil

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1YAzUz-0000Yz-LU@franck.debian.org>
BTS author: Bdale Garbee <bdale@gag.com>

Source: plinth
Source-Version: 0.4.4-1

We believe that the bug you reported is fixed in the latest version of
plinth, which is due to be installed in the Debian FTP archive.

A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 765916@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Bdale Garbee <bdale@gag.com> (supplier of updated plinth package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@ftp-master.debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Format: 1.8
Date: Tue, 13 Jan 2015 22:25:07 +1300
Source: plinth
Binary: plinth
Architecture: source all
Version: 0.4.4-1
Distribution: unstable
Urgency: low
Maintainer: Tzafrir Cohen <tzafrir@debian.org>
Changed-By: Bdale Garbee <bdale@gag.com>
Description:
 plinth     - web front end for administering every aspect of a Freedom Box
Closes: 737456 741919 755619 765916 768666 769328
Changes:
 plinth (0.4.4-1) unstable; urgency=low
 .
   [ Sunil Mohan Adapa ]
   * New upstream version 0.4.4.  Closes: #769328, #755619, #765916,
     #768666, #737456, #741919.
   * Update dependencies as per upstream changes.
   * Require Django 1.7 reflecting upstream changes.
   * Remove patches that have been upstreamed.
   * Update standards version to 3.9.6.
   * Properly remove obsolete module configuration.
   * Remove upstream install documentation.
Checksums-Sha1:
 77b0d68a3ad097a40a97ea1db9de91a1a855f6e6 2232 plinth_0.4.4-1.dsc
 12dfdf68f93578cff3a22430e295cad76f87aef1 1803540 plinth_0.4.4.orig.tar.gz
 fdee6408f88469ecda09628a0d064b3606269cb8 5528 plinth_0.4.4-1.debian.tar.xz
 39c259906642cf38a5bd6a80bcc8b055524470c7 1759476 plinth_0.4.4-1_all.deb
Checksums-Sha256:
 a7d7af62c2f927366c45a79b6e605f7814199c7d068657ff110fdc3cac93c9b6 2232 plinth_0.4.4-1.dsc
 9c97b2f95dc13c76c864bbcce927ddcc92426e345302fce35968ee2470c1fae0 1803540 plinth_0.4.4.orig.tar.gz
 73b9947eb34bbbbfdac3d57ba0552416869e9a916100d7ee41265cacdf6ed780 5528 plinth_0.4.4-1.debian.tar.xz
 ad9b82e957cae4da58af824a8a163774945f412083481e9b1e1f3e276787bdf6 1759476 plinth_0.4.4-1_all.deb
Files:
 7e2dced6aee0474d279c85be9ef0c8de 2232 python optional plinth_0.4.4-1.dsc
 ee5b45f67ab68fb17c6c35ae6f13a2dc 1803540 python optional plinth_0.4.4.orig.tar.gz
 1df59244b2f74995ec5862faa711dfe0 5528 python optional plinth_0.4.4-1.debian.tar.xz
 04fa08d200e229d285a9fe792b957082 1759476 python optional plinth_0.4.4-1_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIVAwUBVLT8FzqTYZbAldlBAQpFXxAAtOuc2+OXKiJTATn2YZ7JKqDov5eiQqNU
yufRDr+9F+Io51UDdJ+Eg1+xnI/IVs9e6+8YjaEt/wXxhhOUqK4e+tIBBtjjmu6C
C1Zl/i0OKeUoUovtvYk3FqFUi+ijmYvYJU0n/iNhzIMARC0RrO5fYrAQXS+C+H39
8PILQUxltNyIb8THxk9kCawlswd/RLn2FLNfpcObe8FgW30UQu7RNoGGVOG+cqkp
JyJ1LMauhTEGmZEcGP1e+0zLD+VNvjVXh6BgnefmuLD80drGMJFaG6VyEwVryEMZ
vC0LiYYeiTwGG4D5hgBIeOSUBSpGmhHxKXdl0COGQfZTT06mV2u8oHD6xiRI1jy7
eAYs6x48eO0ECAClSHyuVsreEd3NqQkuYjil3mauz2i5LtwEuvs9yOS0CAoeHCZq
5ttCgrUCZk5j7KLzt561gvdPqqBdjiZGTuc5mwOFFYyN2JeL1ZabOUhqjRTbQR8U
ZkHMKbV7gxdCu4sI+cjZ6hV1h6w1SVetQmvR9FC0IRNvl07pTblIwWx3fk3gZjj7
duXejkI47a576Cc9URRkEFdZ8cJ2/LvWsfp5ZCaxYIDEmtCjbXYTvp1st7FpUvXW
7gPB34tkpMjQhaJxjqPEXL1R8CL4LsTTYLhjidDsb1CvEPgA7UbAgcICSegUIsIS
csiBGxi1kqg=
=xaQo
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A long time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
