### ISSUE TITLE
GLib.GError: g-io-error-quark: The connection is closed (18)

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#382]
I got a 500 error when accessing https://freedombox.local/plinth/sys/networks/. This is on a Raspberry Pi 2, with 0.7 image and plinth v0.7.2-1. I have a LAN connection and wifi in AP mode. Here's what the log shows:
```
[2016-01-23 14:02:37,500] django.request ERROR    Internal Server Error: /plinth/sys/networks/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/plinth/package.py", line 233, in wrapper
    return func(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/plinth/modules/networks/networks.py", line 53, in index
    connections = network.get_connection_list()
  File "/usr/lib/python3/dist-packages/plinth/network.py", line 219, in get_connection_list
    client = nm.Client.new(None)
GLib.GError: g-io-error-quark: The connection is closed (18)
```

**Comment by phylophyl** [comment]
#383
