### ISSUE TITLE
Monkeysphere: Importing key fails

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#429]
I have the current git master of Plinth in a VM, running via `sudo ./run --no-daemon --debug --server_dir=/plinth`.

When trying to import a key I get the following error:

```
plinth.actions ERROR    Error executing command - ['sudo', '-n', '/home/fonfon/code/plinth/actions/monkeysphere', 'host-import-key', '29:eb:...'], , Traceback (most recent call last):

  File "/home/fonfon/code/plinth/actions/monkeysphere", line 236, in <module>
    main()
  File "/home/fonfon/code/plinth/actions/monkeysphere", line 232, in main
    subcommand_method(arguments)
  File "/home/fonfon/code/plinth/actions/monkeysphere", line 194, in subcommand_host_import_key
    key['available_domains'][0]], env=env)
IndexError: list index out of range
```

**Comment by SunilMohanAdapa** [comment]
On Monday 14 March 2016 04:40 PM, fonfon wrote:
> I have the current git master of Plinth in a VM, running via |sudo ./run
> --no-daemon --debug --server_dir=/plinth|.
> 
> When trying to import a key I get the following error:
> 
> |plinth.actions ERROR Error executing command - ['sudo', '-n',
> '/home/fonfon/code/plinth/actions/monkeysphere', 'host-import-key',
> '29:eb:...'], , Traceback (most recent call last): File
> "/home/fonfon/code/plinth/actions/monkeysphere", line 236, in <module>
> main() File "/home/fonfon/code/plinth/actions/monkeysphere", line 232,
> in main subcommand_method(arguments) File
> "/home/fonfon/code/plinth/actions/monkeysphere", line 194, in
> subcommand_host_import_key key['available_domains'][0]], env=env)
> IndexError: list index out of range |
> 

I guess this means there is a key which does not have any domains
associated with it.  This can happen with snakeoil certificate and SSH
keys when there are no domains configured on the system.  Does the names
module show any domains (from PageKite or Hidden Service or System
configured domain)?  Could you please try adding a domain (atleast a
hidden service)?

-- 
Sunil

**Comment by fonfon** [comment]
I added a hidden service and the import works now.

**Comment by SunilMohanAdapa** [comment]
On 03/14/2016 07:52 PM, fonfon wrote:
> I added a hidden service and the import works now.
> 

We all we need to do is change the interface in this scenario so that:

1) Show 'No domains available' instead of list of domains next to the key.

2) Disable the 'import key' button.

-- 
Sunil
