### ISSUE TITLE
"Can't contact LDAP server" error during users setup

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#500]
When building an image with freedom-maker, using (unreleased) freedombox-setup 0.9.2 and plinth 0.9.3, there are errors during users module setup:
```
[2016-06-12 21:43:48,201] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'setup'], , ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)
Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 198, in <module>
    main()
  File "/usr/share/plinth/actions/users", line 194, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/users", line 85, in subcommand_setup
    configure_slapd()
  File "/usr/share/plinth/actions/users", line 95, in configure_slapd
    setup_admin()
  File "/usr/share/plinth/actions/users", line 129, in setup_admin
    check=True, stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapsearch', '-Q', '-L', '-L', '-L', '-Y', 'EXTERNAL', '-H', 'ldapi:///', '-s', 'base', '-b', 'olcDatabase={1}mdb,cn=config', '(objectclass=*)', 'olcRootDN', 'olcRootPW']' returned non-zero exit status 255

[2016-06-12 21:43:48,202] plinth.setup   ERROR    Error running setup - ('users', '', 'ldap_sasl_interactive_bind_s: Can\'t contact LDAP server (-1)\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 198, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 194, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 85, in subcommand_setup\n    configure_slapd()\n  File "/usr/share/plinth/actions/users", line 95, in configure_slapd\n    setup_admin()\n  File "/usr/share/plinth/actions/users", line 129, in setup_admin\n    check=True, stdout=subprocess.PIPE)\n  File "/usr/lib/python3.5/subprocess.py", line 708, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-L\', \'-L\', \'-L\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'olcDatabase={1}mdb,cn=config\', \'(objectclass=*)\', \'olcRootDN\', \'olcRootPW\']\' returned non-zero exit status 255\n')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plinth/setup.py", line 77, in run
    self.module.setup(self, old_version=current_version)
  File "/usr/lib/python3/dist-packages/plinth/modules/users/__init__.py", line 51, in setup
    helper.call('post', actions.superuser_run, 'users', ['setup'])
  File "/usr/lib/python3/dist-packages/plinth/setup.py", line 107, in call
    return method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/plinth/actions.py", line 118, in superuser_run
    return _run(action, options, input, async, True)
  File "/usr/lib/python3/dist-packages/plinth/actions.py", line 180, in _run
    raise ActionError(action, output, error)
plinth.errors.ActionError: ('users', '', 'ldap_sasl_interactive_bind_s: Can\'t contact LDAP server (-1)\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 198, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 194, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 85, in subcommand_setup\n    configure_slapd()\n  File "/usr/share/plinth/actions/users", line 95, in configure_slapd\n    setup_admin()\n  File "/usr/share/plinth/actions/users", line 129, in setup_admin\n    check=True, stdout=subprocess.PIPE)\n  File "/usr/lib/python3.5/subprocess.py", line 708, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-L\', \'-L\', \'-L\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'olcDatabase={1}mdb,cn=config\', \'(objectclass=*)\', \'olcRootDN\', \'olcRootPW\']\' returned non-zero exit status 255\n')
[2016-06-12 21:43:48,203] plinth.__main__ ERROR    Error running setup - ('users', '', 'ldap_sasl_interactive_bind_s: Can\'t contact LDAP server (-1)\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 198, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 194, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 85, in subcommand_setup\n    configure_slapd()\n  File "/usr/share/plinth/actions/users", line 95, in configure_slapd\n    setup_admin()\n  File "/usr/share/plinth/actions/users", line 129, in setup_admin\n    check=True, stdout=subprocess.PIPE)\n  File "/usr/lib/python3.5/subprocess.py", line 708, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-L\', \'-L\', \'-L\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'olcDatabase={1}mdb,cn=config\', \'(objectclass=*)\', \'olcRootDN\', \'olcRootPW\']\' returned non-zero exit status 255\n')
```
This prevents Plinth from adding users to LDAP.

**Comment by jvalleroy** [comment]
This error was due to another LDAP server running on the host system.
