### ISSUE TITLE
TypeError in first_boot

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#506]
I found this exception in plinth's log while testing this image:
http://ftp.skolelinux.org/pub/freedombox/0.9-rc1/freedombox-unstable-free_0.9_all-amd64.vdi.xz

```
[2016-06-28 11:09:24,619] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'create-user', 'tester']
[2016-06-28 11:09:24,807] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'add-user-to-group', 'tester', 'admin']
[2016-06-28 11:09:25,013] django.request ERROR    Internal Server Error: /plinth/firstboot/state10/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 248, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 186, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 184, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/plinth/modules/first_boot/views.py", line 73, in state10
    context_instance=RequestContext(request))
TypeError: render_to_response() got an unexpected keyword argument 'context_instance'
[2016-06-28 11:15:33,987] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/ssh', 'get-keys', '--username', 'tester']
```

Also the apps list doesn't appear in plinth in this image. (It works fine in the i386 image though.) Not sure if that is related.

**Comment by jvalleroy** [comment]
@SunilMohanAdapa I don't see this issue when rebuilding virtualbox-amd64 image. Could there have been a temporary issue during the 0.9-rc1 image build?

**Comment by SunilMohanAdapa** [comment]
On 06/30/2016 07:22 PM, James Valleroy wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa> I don't see this
> issue when rebuilding virtualbox-amd64 image. Could there have been a
> temporary issue during the 0.9-rc1 image build?

I read that Django 1.10 beta was accidentally uploaded in unstable and
was later corrected. https://tracker.debian.org/pkg/python-django . The
date certainly coincides with our build date.

I shall make fresh builds and upload them.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
I can confirm that in 0.9-rc2 images that I have just uploaded, that problem is gone.  I believe this bug is now fixed.
