### ISSUE TITLE
500

### ISSUE THREAD

**Issue by dieterth** [freedombox/Plinth#507]
Hi,

my new freedombox give me an order:
Dies ist ein interner Fehler und nicht etwas, das Sie verursacht haben oder beheben können. Bitte melden Sie den Fehler auf dem Bugtracker, so dass wir es beheben können. 

This is an error you cant self correct, please create an ticket.
Best Regards,

Dieter

**Comment by SunilMohanAdapa** [comment]
On 06/28/2016 09:26 PM, Dieter wrote:
> Hi,
> 
> my new freedombox give me an order:
> Dies ist ein interner Fehler und nicht etwas, das Sie verursacht haben
> oder beheben können. Bitte melden Sie den Fehler auf dem Bugtracker, so
> dass wir es beheben können.
> 
> This is an error you cant self correct, please create an ticket.
> Best Regards,
> 

Could you please check /var/log/syslog ? It would contain the full error
message that plinth is trowing.  That would be helpful in fixing the issue.

Also what leads to this error?  What operation did you perform?

-- 
Sunil

**Comment by dieterth** [comment]
Hi Sunil,

i am new with the fb, and iam playing around in plinth.
I think, there was an update of avahi programs from the repo, in syslog i can find the atached data.
Plint isnt starting no more.
#--------
dth@freedombox:/var/log# cat syslog | plinth
[2016-06-28 18:42:54,796] plinth.__main__ INFO     Configured Django with applications - ['bootstrapform', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'stronghold', 'plinth', 'plinth.modules.apps', 'plinth.modules.avahi', 'plinth.modules.config', 'plinth.modules.datetime', 'plinth.modules.deluge', 'plinth.modules.diagnostics', 'plinth.modules.dynamicdns', 'plinth.modules.firewall', 'plinth.modules.first_boot', 'plinth.modules.help', 'plinth.modules.ikiwiki', 'plinth.modules.mumble', 'plinth.modules.names', 'plinth.modules.networks', 'plinth.modules.openvpn', 'plinth.modules.owncloud', 'plinth.modules.pagekite', 'plinth.modules.power', 'plinth.modules.privoxy', 'plinth.modules.roundcube', 'plinth.modules.shaarli', 'plinth.modules.system', 'plinth.modules.tor', 'plinth.modules.transmission', 'plinth.modules.upgrades', 'plinth.modules.users', 'plinth.modules.xmpp', 'plinth.modules.letsencrypt', 'plinth.modules.minetest', 'plinth.modules.monkeysphere', 'plinth.modules.quassel', 'plinth.modules.radicale', 'plinth.modules.repro', 'plinth.modules.ttrss']
[2016-06-28 18:42:54,803] plinth.__main__ INFO     Creating or adding new tables to data file
Operations to perform:
  Apply all migrations: auth, contenttypes, plinth
Running migrations:
  No migrations to apply.
[2016-06-28 18:42:55,694] plinth.__main__ INFO     Configuration loaded from file - /etc/plinth/plinth.config
[2016-06-28 18:42:55,701] plinth.__main__ INFO     Script prefix - /plinth
[2016-06-28 18:42:55,704] plinth.module_loader INFO     Importing plinth.modules.apps
[2016-06-28 18:42:55,710] plinth.module_loader INFO     Importing plinth.modules.avahi
[2016-06-28 18:42:55,717] plinth.module_loader INFO     Importing plinth.modules.config
[2016-06-28 18:42:55,722] plinth.module_loader INFO     Importing plinth.modules.datetime
[2016-06-28 18:42:55,736] plinth.module_loader INFO     Importing plinth.modules.deluge
[2016-06-28 18:42:55,742] plinth.module_loader INFO     Importing plinth.modules.diagnostics
[2016-06-28 18:42:55,757] plinth.module_loader INFO     Importing plinth.modules.dynamicdns
[2016-06-28 18:42:55,781] plinth.module_loader INFO     Importing plinth.modules.firewall
[2016-06-28 18:42:55,788] plinth.module_loader INFO     Importing plinth.modules.first_boot
[2016-06-28 18:42:56,219] plinth.module_loader INFO     Importing plinth.modules.help
[2016-06-28 18:42:56,224] plinth.module_loader INFO     Importing plinth.modules.ikiwiki
[2016-06-28 18:42:56,241] plinth.module_loader INFO     Importing plinth.modules.mumble
[2016-06-28 18:42:56,246] plinth.module_loader INFO     Importing plinth.modules.names
[2016-06-28 18:42:56,253] plinth.module_loader INFO     Importing plinth.modules.networks
[2016-06-28 18:42:56,284] plinth.module_loader INFO     Importing plinth.modules.openvpn
[2016-06-28 18:42:56,308] plinth.module_loader INFO     Importing plinth.modules.owncloud
[2016-06-28 18:42:56,314] plinth.module_loader INFO     Importing plinth.modules.pagekite
[2016-06-28 18:42:56,340] plinth.module_loader INFO     Importing plinth.modules.power
[2016-06-28 18:42:56,347] plinth.module_loader INFO     Importing plinth.modules.privoxy
[2016-06-28 18:42:56,352] plinth.module_loader INFO     Importing plinth.modules.roundcube
[2016-06-28 18:42:56,357] plinth.module_loader INFO     Importing plinth.modules.shaarli
[2016-06-28 18:42:56,362] plinth.module_loader INFO     Importing plinth.modules.system
[2016-06-28 18:42:56,368] plinth.module_loader INFO     Importing plinth.modules.tor
[2016-06-28 18:42:56,383] plinth.module_loader INFO     Importing plinth.modules.transmission
[2016-06-28 18:42:56,397] plinth.module_loader INFO     Importing plinth.modules.upgrades
[2016-06-28 18:42:56,410] plinth.module_loader INFO     Importing plinth.modules.users
[2016-06-28 18:42:56,448] plinth.module_loader INFO     Importing plinth.modules.xmpp
[2016-06-28 18:42:56,453] plinth.module_loader INFO     Importing plinth.modules.letsencrypt
[2016-06-28 18:42:56,460] plinth.module_loader INFO     Importing plinth.modules.minetest
[2016-06-28 18:42:56,466] plinth.module_loader INFO     Importing plinth.modules.monkeysphere
[2016-06-28 18:42:56,473] plinth.module_loader INFO     Importing plinth.modules.quassel
[2016-06-28 18:42:56,478] plinth.module_loader INFO     Importing plinth.modules.radicale
[2016-06-28 18:42:56,483] plinth.module_loader INFO     Importing plinth.modules.repro
[2016-06-28 18:42:56,488] plinth.module_loader INFO     Importing plinth.modules.ttrss
[2016-06-28 18:42:56,582] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/tor', 'get-hs']
[2016-06-28 18:42:59,488] plinth.modules.names INFO     Added domain o3hlwrifnpacdozy.onion of type hiddenservice with services ['http', 'https', 'ssh']
[2016-06-28 18:42:59,605] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
Failed to dump process list, ignoring: Unit pagekite.service not found.
[2016-06-28 18:43:02,564] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
[2016-06-28 18:43:05,502] plinth.__main__ INFO     Setting up CherryPy server
[28/Jun/2016:18:43:05] ENGINE Listening for SIGUSR1.
[28/Jun/2016:18:43:05] ENGINE Listening for SIGTERM.
[28/Jun/2016:18:43:05] ENGINE Listening for SIGHUP.
[28/Jun/2016:18:43:05] ENGINE Bus STARTING
[28/Jun/2016:18:43:05] ENGINE Started monitor thread '_TimeoutMonitor'.
[28/Jun/2016:18:43:10] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0xb6035bb0>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python3/dist-packages/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
OSError: Port 8000 not free on '127.0.0.1'

[28/Jun/2016:18:43:10] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python3/dist-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("Port 8000 not free on '127.0.0.1'",)

[28/Jun/2016:18:43:10] ENGINE Bus STOPPING
[28/Jun/2016:18:43:10] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8000)) already shut down
[28/Jun/2016:18:43:10] ENGINE Stopped thread '_TimeoutMonitor'.
[28/Jun/2016:18:43:10] ENGINE Bus STOPPED
[28/Jun/2016:18:43:10] ENGINE Bus EXITING
[28/Jun/2016:18:43:10] ENGINE Bus EXITED

**Comment by dieterth** [comment]
Hmm,

wy the ticket is closed?

sorry.

**Comment by jvalleroy** [comment]
@dieterth I think you meant to run "cat syslog | grep plinth". The grep was left out so it started a 2nd instance of plinth.

**Comment by SunilMohanAdapa** [comment]
On 06/29/2016 12:06 AM, Dieter wrote:
> Ok, i see, Thank you!
> 
> Am 28.06.2016 um 19:22 schrieb James Valleroy:
>> @dieterth <https://github.com/dieterth> I think you meant to run "cat
>> syslog | grep plinth". The grep was left out so it started a 2nd
>> instance of plinth.
>>

Does it also fix the original problem of getting uncorrectable errors on
your Plinth page?

-- 
Sunil

**Comment by dieterth** [comment]
No, but i have reset the Box and take a newer Image to test it.
Maybe this error sitt in front off the Screen.
:)
The Image i used was an older one, ~0.7? now i use the newest one.

Thank you for your great Work!
Dieter
