### ISSUE TITLE
RuntimeError: OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#514]
When trying to run all diagnostics (using 0.9-rc2 raspberry2 image), I got this error:
```
[2016-07-09 16:05:31,603] django.request ERROR    Internal Server Error: /plinth/sys/diagnostics/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/django/template/context.py", line 264, in bind_template
    yield
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 179, in render
    for i, item in enumerate(values):
RuntimeError: OrderedDict mutated during iteration
```

**Comment by jvalleroy** [comment]
After returning to the Diagnostics page, I am able to see the results of the previous run. Running all diagnostics again did not reproduce the error.

**Comment by SunilMohanAdapa** [comment]
On 07/10/2016 01:39 AM, James Valleroy wrote:
> When trying to run all diagnostics (using 0.9-rc2 raspberry2 image), I
> got this error:

The error is due to the diagnostics results array being iterated at the
same time a new diagnostics result is being inserted.  Understandably
this is a bit rare.

The fix is to update the diagnostics results in a thread safe way.

-- 
Sunil
