### ISSUE TITLE
Monkeysphere error 500

### ISSUE THREAD

**Issue by Irianx** [freedombox/Plinth#521]
Hi. I tried to use monkeysphere and get now only the error 500 (no more access to monkeysphere). How to get out of this problem? Here the content of plinth.log in case of opening monkeysphere:

[2016-07-17 17:01:56,880] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/monkeysphere', 'host-show-keys']
[2016-07-17 17:01:59,132] django.request ERROR    Internal Server Error: /plinth/sys/monkeysphere/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/plinth/modules/monkeysphere/views.py", line 40, in index
    status = get_status()
  File "/usr/lib/python3/dist-packages/plinth/modules/monkeysphere/views.py", line 98, in get_status
    return {'keys': get_keys()}
  File "/usr/lib/python3/dist-packages/plinth/modules/monkeysphere/views.py", line 112, in get_keys
    if '*' in key['available_domains']:
KeyError: 'available_domains'

**Comment by SunilMohanAdapa** [comment]
This was a rather nasty problem.  Fixed in #573 .
