### ISSUE TITLE
Snapshot fails to install

### ISSUE THREAD

**Issue by marxistvegan** [freedombox/Plinth#568]
This is on the Pi Zero and I get the below message in plinth
`Error installing application: ('snapshot', '', 'Creating config failed (/sbin/chsnap not installed).\nTraceback (most recent call last):\n File "/usr/share/plinth/actions/snapshot", line 161, in <module>\n main()\n File "/usr/share/plinth/actions/snapshot", line 157, in main\n subcommand_method(arguments)\n File "/usr/share/plinth/actions/snapshot", line 61, in subcommand_setup\n subprocess.run(command, check=True)\n File "/usr/lib/python3.5/subprocess.py", line 708, in run\n output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'snapper\', \'create-config\', \'/\']\' returned non-zero exit status 1\n')`

**Comment by SunilMohanAdapa** [comment]
On 08/27/2016 09:03 PM, Stephen wrote:
> This is on the Pi Zero and I get the below message in plinth

The Raspberry Pi, the filesystem is ext4 and not btrfs.  Although
snapper seems to claim the ability to work on ext4 also, I don't how
that would work.

Perhaps the only thing we should look for is to show a better error
message that snapshotting is on supported due to filesystem type.  This
should be useful for people installing freedombox package on regular Debian.

On a positive note, we might get support for booting with Debian kernel
for Raspberry Pi soon (and hence btrfs too).

-- 
Sunil

**Comment by mray** [comment]
I also get this error message on Raspberry Pi 2B.
A general idea to first perform checks if the install is even possible makes much sense.
There could be an option to try installing it anyway, but with a  notice of why it probably fails.

**Comment by mray** [comment]
This relates to https://github.com/freedombox/Plinth/issues/1147
