### ISSUE TITLE
installing Gobby fails

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#747]
```Error installing application: ('infinoted', "Adding group `infinoted' (GID 123) ...\nDone.\nAdding system user `infinoted' (UID 120) ...\nAdding new user `infinoted' (UID 120) with group `infinoted' ...\nCreating home directory `/var/lib/infinoted' ...\n", '[Sun Mar 5 10:07:46 2017] INFO: Generating 4096 bit RSA private key...\n[Sun Mar 5 10:08:15 2017] INFO: Generating self-signed certificate...\n[Sun Mar 5 10:08:17 2017] INFO: Loaded plugin "note-text" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-note-text.so"\n[Sun Mar 5 10:08:17 2017] INFO: Loaded plugin "autosave" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-autosave.so"\n[Sun Mar 5 10:08:17 2017] INFO: Loaded plugin "logging" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-logging.so"\n[Sun Mar 5 10:08:17 2017] INFO: Loaded plugin "directory-sync" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-directory-sync.so"\n[Sun Mar 5 10:08:17 2017] INFO: Unloaded plugin "directory-sync" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-directory-sync.so"\n[Sun Mar 5 10:08:17 2017] INFO: Unloaded plugin "logging" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-logging.so"\n[Sun Mar 5 10:08:17 2017] INFO: Unloaded plugin "autosave" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-autosave.so"\n[Sun Mar 5 10:08:17 2017] INFO: Unloaded plugin "note-text" from "/usr/lib/arm-linux-gnueabi/infinoted-0.6/plugins/libinfinoted-plugin-note-text.so"\nCould not kill daemon: Timer expired\nTraceback (most recent call last):\n File "/usr/share/plinth/actions/infinoted", line 179, in <module>\n main()\n File "/usr/share/plinth/actions/infinoted", line 175, in main\n subcommand_method(arguments)\n File "/usr/share/plinth/actions/infinoted", line 157, in subcommand_setup\n subprocess.run([\'infinoted\', \'--kill-daemon\'], check=True)\n File "/usr/lib/python3.5/subprocess.py", line 398, in run\n output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'infinoted\', \'--kill-daemon\']\' returned non-zero exit status 255\n') ```

here is how it looks:

![image](https://cloud.githubusercontent.com/assets/164785/23586402/3f935c70-0194-11e7-89c3-396c3c451166.png)

...this is bad. This really isn't even a useful error message. No idea what to do.

**Comment by jvalleroy** [comment]
It looks like there was a timeout while trying to restart the service. We will need to increase the timeouts to avoid this error. The timeout is currently not specified in infinoted's service file, so it's just the default.

What hardware are you using? Do you get the same error again if you try the Install again?

**Comment by mray** [comment]
- I'm running FreedomBox from a Raspberry Pi (first generation). 
- just hitting the "install" button again worked this time
- unfortunately it now shows as being installed but not running for some reason
![image](https://cloud.githubusercontent.com/assets/164785/23589403/9b5c4e12-01cc-11e7-97c5-d64f7ab191c2.png)
- I then disabled and enabled again, still not running
- diagnostics shows this:
![image](https://cloud.githubusercontent.com/assets/164785/23589438/60c352e0-01cd-11e7-8f41-a820dd033fa2.png)

**Comment by jvalleroy** [comment]
I'm seeing the same issue on Raspberry Pi 2. Due to the timeout error, the certificate files were created, but are owned by "root" instead of "infinoted":
```
# ls -al /etc/infinoted/
total 8
drwxr-x--- 1 infinoted infinoted   70 Aug  1 11:23 .
drwxr-xr-x 1 root      root      2756 Aug  1 11:22 ..
-rw-r----- 1 root      root      1753 Aug  1 11:23 infinoted-cert.pem
-rw-r----- 1 root      root      3243 Aug  1 11:23 infinoted-key.pem
```
After fixing the ownership with ```# chown infinoted:infinoted /etc/infinoted/*```, I was able to start infinoted through Plinth.

Besides fixing the timeout, we can also adjust the setup script (https://github.com/freedombox/Plinth/blob/master/actions/infinoted#L162), so that the ownership of these files will be set during module setup, regardless of whether the files already exist.

**Comment by mray** [comment]
the command does notwork for me:
```
~$ sudo chown infinoted:infinoted /etc/infinoted/*
chown: cannot access '/etc/infinoted/*': No such file or directory
```
that is what I see:
![image](https://user-images.githubusercontent.com/164785/28860770-28689958-775e-11e7-933f-1f5ab57b8325.png)

Checking the Enable button changes nothing, plinth comes up with the same result all the time.

**Comment by mray** [comment]
permissions still look like that:

```
total 16
drwxr-x---   2 infinoted infinoted 4096 Jul 27 20:39 .
drwxr-xr-x 107 root      root      4096 Aug  2 06:42 ..
-rw-r-----   1 root      root      1753 Jul 27 20:39 infinoted-cert.pem
-rw-r-----   1 root      root      3243 Jul 27 20:39 infinoted-key.pem
```

**Comment by jvalleroy** [comment]
@mray Could you try becoming root with "sudo su", then run the command?

**Comment by mray** [comment]
Logging in via ssh and doing `sudo su` and then`chown infinoted:infinoted /etc/infinoted/*` seems to have worked: after a restart Gobby server runs finally.

*Thanks for your input!*

I don't want to close this, since this isn't a "solution" of the issue though. The server should should run fine without those commands.

**Comment by jvalleroy** [comment]
Yes, I believe there are 2 changes needed:
- [ ] Make the infinoted setup script always check the ownership of certificate files (not just when the files are created).
- [ ] Find a good service timeout value that will work for our targeted hardware. Apply that to services that have long running startup/shutdown.
