### ISSUE TITLE
500 error on Firewall page

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#748]
On Plinth version 0.13.1. It looks like firewalld is not running for some reason, I will investigate that further. But anyway, the Firewall page shows a 500 error, here is the log:
```
[2017-03-05 12:49:43,145] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/firewall', 'get-status']
[2017-03-05 12:49:43,463] django.request ERROR    Internal Server Error: /plinth/sys/firewall/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/plinth/modules/firewall/views.py", line 30, in index
    if not firewall.get_enabled_status():
  File "/usr/lib/python3/dist-packages/plinth/modules/firewall/__init__.py", line 68, in get_enabled_status
    return output.split()[0] == 'running'
IndexError: list index out of range
```

**Comment by SunilMohanAdapa** [comment]
This is a simple error in retrieving the status of the firewall from the firewall-cmd command.  Investigate the cause and fix the error.

**Comment by SunilMohanAdapa** [comment]
To reproduce the problem, run `systemctl stop firewalld` and visit the firewall page in the configuration section of Plinth UI.

**Comment by kkampardi** [comment]
Hi I'd like to work on this one!

**Comment by SunilMohanAdapa** [comment]
@kkampardi , please go ahead and work on this one.   Your assessment it correct so far.  Tests are very much appreciated but we don't insist on test cases (yet :) ).

**Comment by kkampardi** [comment]
@SunilMohanAdapa  There is some progress here. After some logging the problem seems to be that the python script reads `stdout` to get the `output` but the firewalld writes to `stderr`  when the firewalld is down so the `output` is empty and causes the `IndexError`. I will make a pr with a possible solution

```
[2017-04-13 09:31:30,089] plinth.modules.firewall INFO     Logging: Start getting status
[2017-04-13 09:31:30,091] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/firewall', 'get-status']
[2017-04-13 09:31:30,473] plinth.modules.firewall INFO     output: 
[2017-04-13 09:31:30,473] plinth.modules.firewall INFO     Logging: Finish getting status
[2017-04-13 09:31:30,473] django.request ERROR    Internal Server Error: /plinth/sys/firewall/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Plinth-0.14.0-py3.5.egg/plinth/modules/firewall/views.py", line 30, in index
    if not firewall.get_enabled_status():
  File "/usr/local/lib/python3.5/dist-packages/Plinth-0.14.0-py3.5.egg/plinth/modules/firewall/__init__.py", line 75, in get_enabled_status
    return output.split()[0] == 'running'
IndexError: list index out of range
```
