### ISSUE TITLE
Fix failing disk test: test_btrfs_expansion

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#780]
The following test which only gets executed when run as root, is failing. Investigate and fix the issue.

```
======================================================================
ERROR: test_btrfs_expansion (plinth.modules.disks.tests.test_disks.TestActions)
Test that btrfs file system can be expanded.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/plinth/modules/disks/tests/test_disks.py", line 184, in test_btrfs_expansion
    self.assert_btrfs_file_system_healthy(1)
  File "/vagrant/plinth/modules/disks/tests/test_disks.py", line 233, in assert_btrfs_file_system_healthy
    stderr=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['btrfs', 'check', '/dev/loop0p1']' returned non-zero exit status 251
```

**Comment by JoKeyser** [comment]
This may be the ultimate beginner question, but I don't get how to even recreate this error...
I've tried by running `setup.py test`, and get this output (sorry for the long dump):

```
root@freedombox:/vagrant# ./setup.py test
running test
running egg_info
writing Plinth.egg-info/PKG-INFO
writing top-level names to Plinth.egg-info/top_level.txt
writing dependency_links to Plinth.egg-info/dependency_links.txt
writing requirements to Plinth.egg-info/requires.txt
package init file 'plinth/locale/__init__.py' not found (or not a regular file)
package init file 'plinth/modules/jsxc/static/__init__.py' not found (or not a regular file)
package init file 'plinth/modules/jsxc/static/libjs-jsxc/__init__.py' not found (or not a regular file)
package init file 'plinth/modules/pagekite/templatetags/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/zh_Hans/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/da/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/es/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/gu/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/nl/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/nb/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/ru/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/te/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/sv/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/fa/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/de/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/tr/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/pl/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/id/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/ja/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/pt/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/fake/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/fr/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/hi/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/it/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/zh_Hans/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/da/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/es/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/gu/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/nl/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/nb/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/ru/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/te/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/sv/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/fa/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/de/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/tr/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/pl/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/id/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/ja/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/pt/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/fake/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/fr/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/hi/LC_MESSAGES/__init__.py' not found (or not a regular file)
package init file 'plinth/locale/it/LC_MESSAGES/__init__.py' not found (or not a regular file)
writing manifest file 'Plinth.egg-info/SOURCES.txt'
running build_ext
Creating test database for alias 'default'...
.............................Configuration does not contain option: Path.file_root
.Configuration does not contain option: Path.root
.................................Unit tor@plinth.service could not be found.
...
----------------------------------------------------------------------
Ran 66 tests in 15.873s

OK
Destroying test database for alias 'default'...
```

**Comment by SunilMohanAdapa** [comment]
Err... I tried to reproduce this problem yesterday and could not reproduce it myself.  I looked at the code and I could see only one place that could cause this kind of a problem.  If cleanup didn't happen properly in an earlier test run, then losetup will run on the same file again and produce bad results.  To, simulate the problem I commented out the cleanup steps in Disk:__exit__() and ran the tests.  After I uncommented the steps later, I could not get the tests to work properly and most of them started to fail continuously.

I believe a good fix to the problem would be to get a new disk file name for every test by modifying Disk():_create_disk_file().  This way if tests are terminated before they can cleanup, only problem would be some left over files in the test directory but not failure of future tests.

**Comment by JoKeyser** [comment]
Thanks for looking into this. I'm not sure whether I quite follow. My first question was whether the output I see was expected, or actually my setup was wrong, but that seems answered - it's fine, and actually the disks test went without error. Can confirm that commenting out the commands in `__exit__` in `plinth/modules/disks/tests/test_disks.py` leads to persistent failure, even after commenting them in :).

So to clarify, do you think now that the originally failed test was a fluke? I mean, was it "just" a failed test-setup that happens occasionally? And the way forward is to improve the test, using the proposed solution in your 2nd paragraph?

**Comment by SunilMohanAdapa** [comment]
On Wednesday 12 April 2017 04:49 AM, Johannes Keyser wrote:
> Thanks for looking into this. I'm not sure whether I quite follow.
> My first question was whether the output I see was expected, or
> actually my setup was wrong, but that seems answered - it's fine, and
> actually the disks test went without error. Can confirm that
> commenting out the commands in |__exit__| in
> |plinth/modules/disks/tests/test_disks.py| leads to persistent
> failure, even after commenting them in :).
> 
> So to clarify, do you think now that the originally failed test was
> a fluke? I mean, was it "just" a failed test-setup that happens 
> occasionally?

I believe that the tests pass very consistently if they are run
uninterrupted (I tried several times).  I now think that the my original
bug report situation was due to an improper termination of the tests.  I
must have pressed Control-C during a test run leading to the bug I
reported in the next run.  Sorry for not mentioning this explicitly
before :)

> And the way forward is to improve the test, using the proposed
> solution in your 2nd paragraph?

Yes.

-- 
Sunil

**Comment by JoKeyser** [comment]
Hi Sunil, I think my PR #870 is a simpler solution. What do you think?
