### ISSUE TITLE
sso: Need upgrade path

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#875]
This was mentioned in the progress call, but I think there's no issue open for it yet.

Currently, for sso, the mod-auth-pubtkt keys are generated in plinth firstboot. This will work for new installs, but not for upgraded systems.

One idea that came up in the meeting:
- [X] Generate keys in sso module setup.
- [X] Equivalent of "plinth setup" would happen at every plinth start -- would run setup for all essential modules, if needed.
- [x] No longer run "plinth setup" from freedombox-setup. So that live images won't contain generated keys.

**Comment by JosephKiranBabu** [comment]
Built a FreedomBox virtualbox image with `plinth --setup-no-install` removed from the file `86_plinth`
Cannot access plinth anymore.

<img width="564" alt="screen shot 2017-08-25 at 4 47 45 pm" src="https://user-images.githubusercontent.com/4830191/29712002-445e155c-89b5-11e7-9088-f16ddfb7396b.png">

**Comment by jvalleroy** [comment]
@JosephKiranBabu I also tested this. I was able to access Plinth finally after rebooting the VM again. But there was an issue with LDAP for creating the user.
```
Aug 26 10:31:30 freedombox plinth[475]: [2017-08-26 10:31:30,758] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'create-user', 'tester']
Aug 26 10:31:30 freedombox plinth[475]: [2017-08-26 10:31:30,863] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'create-user', 'tester'], , Error adding user tester to LDAP
Aug 26 10:31:30 freedombox plinth[475]: [2017-08-26 10:31:30,864] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'add-user-to-group', 'tester', 'admin']
Aug 26 10:31:30 freedombox slapd[1020]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Aug 26 10:31:30 freedombox plinth[475]: [2017-08-26 10:31:30,952] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'add-user-to-group', 'tester', 'admin'], , Cannot resolve uid tester to user : not found
```

I think one issue is that freedombox-setup first-run ldap setup needs to be run **after** the users module setup is complete.

**Comment by jvalleroy** [comment]
Found this error in /var/log/freedombox-first-run.log:
```
+ /usr/share/plinth/actions/users first-run
ldap_add: Server is unwilling to perform (53)
	additional info: no global superior knowledge
Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 95, in create_organizational_unit
    stdout=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapsearch', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///', '-s', 'base', '-b', 'ou=users,dc=thisbox', '(objectclass=*)']' returned non-zero exit status 32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 170, in <module>
    main()
  File "/usr/share/plinth/actions/users", line 166, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/users", line 59, in subcommand_first_run
    configure_ldap_structure()
  File "/usr/share/plinth/actions/users", line 81, in configure_ldap_structure
    create_organizational_unit('users')
  File "/usr/share/plinth/actions/users", line 105, in create_organizational_unit
    check=True)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapadd', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///']' returned non-zero exit status 53
```
Perhaps we can move the "users first-run" step to the end of users module setup.

**Comment by jvalleroy** [comment]
@JosephKiranBabu I found that testing image builds are working better than unstable, at the moment. Seems to be some issue with systemd in unstable.

**Comment by jvalleroy** [comment]
Fixed.
