### ISSUE TITLE
Travis build fails while trying to install ruamel.yaml

### ISSUE THREAD

**Issue by JosephKiranBabu** [freedombox/Plinth#877]
https://travis-ci.org/freedombox/Plinth/jobs/243280202

```
  Downloading ruamel.yaml-0.15.7.tar.gz (250kB)

    100% |███████████████████████���████████| 253kB 1.8MB/s 

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-i4qjhnar/ruamel.yaml/setup.py", line 873, in <module>

        main()

      File "/tmp/pip-build-i4qjhnar/ruamel.yaml/setup.py", line 862, in main

        setup(**kw)

      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

        _setup_distribution = dist = klass(attrs)

      File "/home/travis/build/freedombox/Plinth/_venv/lib/python3.4/site-packages/setuptools/dist.py", line 272, in __init__

        _Distribution.__init__(self,attrs)

      File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

        self.finalize_options()

      File "/home/travis/build/freedombox/Plinth/_venv/lib/python3.4/site-packages/setuptools/dist.py", line 327, in finalize_options

        ep.load()(self, ep.name, value)

      File "/home/travis/build/freedombox/Plinth/_venv/lib/python3.4/site-packages/setuptools/dist.py", line 105, in check_extras

        if pkg_resources.invalid_marker(m):

      File "/home/travis/build/freedombox/Plinth/_venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1416, in is_invalid_marker

        cls.evaluate_marker(text)

      File "/home/travis/build/freedombox/Plinth/_venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1532, in _markerlib_evaluate

        for key in env.keys():

    RuntimeError: dictionary changed size during iteration

    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']

    test compiling test_ruamel_yaml

   
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i4qjhnar/ruamel.yaml

The command "pip install -r requirements.txt" failed and exited with 1 during .

Your build has been stopped.

```

**Comment by JoKeyser** [comment]
For what it's worth, I couldn't reproduce this in my vagrant box, even when I tried to follow all the listed steps from the travis log, and specifically trying to install ruamel.yaml version 0.15.7.
I'm at a loss, hopefully somebody else will fix this soon :).

**Comment by jvalleroy** [comment]
It looks like Travis CI uses Ubuntu 14.04, and that is the latest version they support. However I think we could use the Docker feature (https://docs.travis-ci.com/user/docker/) to run the tests with a different image (such as a Debian image: https://hub.docker.com/_/debian/).

**Comment by JoKeyser** [comment]
This sounds like a great idea; that way we could also test on multiple systems, as far as I understand. I've poked around without understanding yet, on the basis of https://docs.travis-ci.com/user/docker/. But what I don't understand from that example is how things get installed into the same container... and finally to call the test suite in there.
But also Travis is new to me, adding another layer of complexity. My head's spinning :).

**Comment by JosephKiranBabu** [comment]
Now Travis is installing version 0.15.9 of ruamel.yaml instead of 0.15.7 and the build is passing. 
https://travis-ci.org/freedombox/Plinth/jobs/245675937

**Comment by JosephKiranBabu** [comment]
Maybe it's just a matter of versions. 
We can set specific versions in the requirements.txt file and run a CI pipeline to try to upgrade to the latest version. If the build passes, the CI makes a commit with the latest versions of the dependencies in requirements.txt
I've heard that this is a common practice in some projects and there must be tools/plugins to do this.
