### ISSUE TITLE
In vagrant image: Translations not working?

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#905]
I've never tested it before, but at least in my vagrant image, translations are not working. That is, it just remains in English. The *only* translated string I can spot is the new LE delete button, of all things...

**Comment by jvalleroy** [comment]
I usually get the translations to work by running "setup.py compile_translations" in the /vagrant folder. It would be nice if this happened automatically though.

**Comment by JoKeyser** [comment]
Thanks, but does that work in your current image? In mine it doesn't, even after another "vagrant provision".

**Comment by JoKeyser** [comment]
Okay sorry, it largely works in a fresh vagrant image.
However there's an error when I run

```
vagrant@freedombox:/vagrant$ sudo ./setup.py compile_translations
running compile_translations
processing file django.po in /vagrant/plinth/locale/hi/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/nb/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/de/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/fr/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/it/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/fa/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/zh_Hans/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/pt/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/cs/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/gu/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/da/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/te/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/ta/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/es/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/tr/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/nl/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/ru/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/ja/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/id/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/sv/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/fake/LC_MESSAGES
processing file django.po in /vagrant/plinth/locale/pl/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/hi/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/nb/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/de/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/fr/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/it/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/fa/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/zh_Hans/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/pt/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/cs/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/gu/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/da/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/te/LC_MESSAGES
processing file django.po in /vagrant/build/lib/plinth/locale/ta/LC_MESSAGES
Traceback (most recent call last):
  File "./setup.py", line 245, in <module>
    'update_translations': UpdateTranslations,
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "./setup.py", line 89, in run
    call_command('compilemessages', verbosity=1)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/compilemessages.py", line 103, in handle
    self.compile_messages(locations)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/compilemessages.py", line 134, in compile_messages
    raise CommandError(msg)
django.core.management.base.CommandError: Execution of msgfmt failed: msgfmt: error while opening "/vagrant/build/lib/plinth/locale/ta/LC_MESSAGES/django.mo" for writing: Protocol error
```

**Comment by JoKeyser** [comment]
If that persists, I can open another issue about it, maybe it goes away with the next Weblate sync.
